version: '3.8'

services:
  app:
    container_name: node-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Use container's node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
