services:
  api:
    image: node:18
    restart: unless-stopped
    ports:
      - "17504:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:example@postgres:5432/classes?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/app
    #No se si esta parte puede mejorar
    command: >
      sh -c "
        cd app
        npm install &&
        npm run start
      "
    

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5439:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: classes
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: