services:
  api:
    build: .
    ports:
      - "17504:3000"
    env_file:
      - .env.template
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:example@db:5432/classes?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped
    

  db:
    image: postgres:15
    restart: always
    ports:
      - "5439:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: classes
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: